# Generated by Django 4.0.4 on 2022-05-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniBlog', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='this is bio', max_length=40, null=True),
        ),
    ]
