# Generated by Django 4.0.4 on 2022-05-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniBlog', '0006_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='../static/img/user.png', null=True, upload_to='blog'),
        ),
    ]
