# Generated by Django 4.0.4 on 2022-05-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniBlog', '0008_remove_profile_profile_pic_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='../static/img/user.png', null=True, upload_to='blog'),
        ),
    ]
