# Generated by Django 4.0.4 on 2022-05-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniBlog', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='this is bio', max_length=150, null=True),
        ),
    ]
