# Generated by Django 4.0.4 on 2022-05-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniBlog', '0012_likemodel_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miniBlog.profile'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='upload_to',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
