# Generated by Django 4.0.4 on 2022-05-31 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniBlog', '0014_blogmodel_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
