# Generated by Django 4.0.4 on 2022-06-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniBlog', '0016_profile_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_varified',
            field=models.BooleanField(default=True),
        ),
    ]
